### PR TITLE
Update 8.txt

### PR DESCRIPTION
**Pull request by adeemaamir240**

### CODE REVIEW

**Comment by Adeema-Amir** [comment]
you are commintion too much

**Comment by adeemaamir240** [comment]
you accept my cooment

**Comment by Adeema-Amir** [comment]
ok 👌

**Comment by adeemaamir240** [comment]
okkay its okay

**Comment by Adeema-Amir** [comment]
but another tim edont do this

**Comment by adeemaamir240** [comment]
but why

**Comment by Adeema-Amir** [comment]
humm....

**Comment by adeemaamir240** [comment]
you are right

**Pull request merged**
